<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.6" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.6" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.6" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.6" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
  </ItemGroup>
</Project>